version: "3.7"

# Mendefinisikan dua layanan
services:

  # Layanan pertama: item-app
  item-app:
    # Menggunakan image yang sudah diunggah ke GitHub Packages
    image: ghcr.io/matthewcalbert/a433-microservices/item-app:v1
    # Mengarahkan port 80 pada host ke port 8080 pada container
    ports:
      - "80:8080"
    # Mengatur kebijakan restart layanan menjadi "always"
    restart: always

  # Layanan kedua: item-db
  item-db:
    # Menggunakan image resmi dari MongoDB versi 3
    image: mongo:3
    # Menggunakan volume bernama "app-db" untuk menyimpan data MongoDB
    volumes:
      - "app-db:/data/db"

# Mendefinisikan volume "app-db" yang digunakan oleh layanan "item-db"
volumes:
  app-db: