version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: "Install Hadolint"
          command: |
            apk add --no-cache curl
            curl -sSL -o hadolint "https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64"
            chmod +x hadolint
            mv hadolint /usr/local/bin/
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to GitHub Packages
          command: |
            echo "$GHCR_PAT" | docker login ghcr.io -u $GHCR_USER --password-stdin
      - run:
          name: Build and Push Image
          command: |
            docker build -t ghcr.io/$GHCR_USER/a433-microservices/karsajobs-ui:latest .
            docker push ghcr.io/$GHCR_USER/a433-microservices/karsajobs-ui:latest

workflows:
  build-and-deploy:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
