version: 2.1

orbs:
  go: circleci/go@1.7.2

jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: "Install Hadolint"
          command: |
            apk add --no-cache curl
            curl -sSL -o hadolint "https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64"
            chmod +x hadolint
            mv hadolint /usr/local/bin/
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile

  test-app:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: Login to GitHub Packages
          command: |
            echo "$GHCR_PAT" | docker login ghcr.io -u $GHCR_USER --password-stdin
      - run:
          name: Build and Push Image
          command: |
            docker build -t ghcr.io/$GHCR_USER/a433-microservices/karsajobs:latest .
            docker push ghcr.io/$GHCR_USER/a433-microservices/karsajobs:latest

workflows:
  build-and-deploy:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
